# Generated by Django 4.1.7 on 2023-04-09 05:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("article_reply", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reply",
            name="updated_at",
            field=models.DateTimeField(auto_created=True, default=""),
        ),
    ]
