# Generated by Django 4.1.7 on 2023-04-09 05:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("article_reply", "0002_alter_reply_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reply",
            name="updated_at",
            field=models.DateTimeField(auto_created=True, null=True),
        ),
    ]
