# Generated by Django 4.1.7 on 2023-03-28 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='createdAt',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
