# Generated by Django 4.1.7 on 2023-03-31 02:45

from django.db import migrations


class Migration(migrations.Migration):
    atomic = True

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='createdAt',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='updatedAt',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='article_like',
            old_name='createdAt',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='createdAt',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='updatedAt',
            new_name='updated_at',
        ),
    ]
